apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-conf
  namespace: infra
data:
  nats.conf: |
    jetstream: enabled

    websocket {
      port: 4223
      no_tls: true
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: infra
spec:
  serviceName: "nats"
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.12.6
        args: ["-c", "/etc/nats/nats.conf"]
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 4223
          name: websocket
        - containerPort: 8222
          name: monitor
        volumeMounts:
        - name: nats-conf
          mountPath: /etc/nats/nats.conf
          subPath: nats.conf
      volumes:
      - name: nats-conf
        configMap:
          name: nats-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: infra
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
  - name: websocket
    port: 4223
    targetPort: 4223
    nodePort: 30001
  - name: monitor
    port: 8222
  type: NodePort
