apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: infra
spec:
  serviceName: "nats"
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.12.6
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: infra
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
  - name: monitor
    port: 8222
