apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
      - name: pyroscope
        image: grafana/pyroscope:2.0.2
        ports:
        - containerPort: 4040
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
        volumeMounts:
        - name: pyroscope-data
          mountPath: /var/lib/pyroscope
      volumes:
      - name: pyroscope-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: infra
spec:
  selector:
    app: pyroscope
  ports:
  - name: http
    port: 4040
    targetPort: http
