// Command gensemconv generates the reserved semantic-convention key catalog.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	dirBytes, err := exec.Command("go", "list", "-f", "{{.Dir}}", "go.opentelemetry.io/otel/semconv/v1.39.0").Output()
	must(err)
	dir := strings.TrimSpace(string(dirBytes))
	file := filepath.Join(dir, "attribute_group.go")
	fset := token.NewFileSet()
	parsed, err := parser.ParseFile(fset, file, nil, 0)
	must(err)

	keys := map[string]struct{}{}
	prefixes := map[string]struct{}{"host.": {}, "process.": {}}
	ast.Inspect(parsed, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok || len(call.Args) == 0 {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		pkg, ok := selector.X.(*ast.Ident)
		if !ok || pkg.Name != "attribute" {
			return true
		}
		if selector.Sel.Name == "Key" {
			if value, ok := stringLiteral(call.Args[0]); ok && value != "" {
				keys[value] = struct{}{}
			}
			return true
		}
		binary, ok := call.Args[0].(*ast.BinaryExpr)
		if !ok || binary.Op != token.ADD {
			return true
		}
		if prefix, ok := stringLiteral(binary.X); ok && strings.HasSuffix(prefix, ".") {
			prefixes[prefix] = struct{}{}
		}
		return true
	})

	delete(keys, "")
	keyList := sorted(keys)
	prefixList := sorted(prefixes)
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package baggageattrs")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var semconvReservedKeys = map[string]struct{}{")
	for _, key := range keyList {
		fmt.Fprintf(&out, "\t%q: {},\n", key)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var semconvReservedPrefixes = []string{")
	for _, prefix := range prefixList {
		fmt.Fprintf(&out, "\t%q,\n", prefix)
	}
	fmt.Fprintln(&out, "}")
	must(os.WriteFile(filepath.Join("semconv_reserved_gen.go"), out.Bytes(), 0o644))
}

func stringLiteral(expr ast.Expr) (string, bool) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	value, err := strconv.Unquote(lit.Value)
	return value, err == nil
}

func sorted(values map[string]struct{}) []string {
	out := make([]string, 0, len(values))
	for value := range values {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
